name: Pull Request Comment
on:
  pull_request:
    types: [opened]

jobs:
  pr-comment:
    runs-on: ubuntu-latest
    steps:
    - name: Comment on new PRs
      uses: actions/github-script@v6
      script: |
        github.rest.issues.createComment({
          owner: context.repo.owner,
          repo: context.repo. 
          issue_number: context.issue.number,
          body: "Thank you for your contribution!."
         });
  