name: Simple ACtion
on: [push]

job:
  simple-action:
    runs-on: ubuntu-latest
    steps:
    - name: Simple js action
      uses: actions/hello-world-javascript-action@3ec9b3854b2b6e6592067b8447fcc3122f858215
      with:
        who-to-greet: nerdycool
    - name: Log greeting Time
      run: echo "$"{{ steps.simple-action.outputs.time }}
    